### PR TITLE
fix to support appium beta servers

### PR DESCRIPTION
**Pull request by SrinivasanTarget**

### CODE REVIEW

**Comment by saikrishna321** [comment]
@SrinivasanTarget Don't you think we need to pull all the capabilities out side the AppiumParallelTest class, and let the user create there own desired caps by specify it in properties file?

**Comment by SrinivasanTarget** [comment]
That's how it is now right. But specifying the common capability in
property file is fine, if in case I need only the first case to have
"autoaccept alerts" (say for eg) and the second case should not have that.
How are we gonna handle that if we give enough freedom to keep it in
property file completely.

**Comment by saikrishna321** [comment]
@SrinivasanTarget we are keeping the capabilties into the property coz if the user wants to add commandTimeout as a part of caps, but right now we are handling the driver instance with very limited caps like appPackage,appActivity,deviceName and platformVersion.

So if we have the freedom for the user to specify the caps in the property file, we can generate the caps hashMap on run time..

Your thoughts ?

**Comment by SrinivasanTarget** [comment]
Yup Got it. Can we have separate property file for Android and iOS each.?
Lets work on that.

**Comment by saikrishna321** [comment]
@SrinivasanTarget +1

**Pull request closed without merging**
