### PR TITLE
Changes done to create adblog in target folder of Window machine

### PR DESCRIPTION
**Pull request by nkrishnac-rpx**

### CODE REVIEW

**Comment by saikrishna321** [comment]
@nkrishnac-rpx don't you think adb logs folder would be created here 
https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/ParallelThread.java#L93

what issue are u facing on windows machine ?

**Comment by nkrishnac-rpx** [comment]
For the first time when i use adbLog folder is not created automatically.

**Comment by nkrishnac-rpx** [comment]
Also i'm running through testNg.xml instead of command line maven execution.

**Comment by saikrishna321** [comment]
@nkrishnac-rpx you need to run from commandLine as testng.xml is created on the fly and is been programatically executed. Your entry point is ParallelThread.java

**Comment by nkrishnac-rpx** [comment]
Ok shall i close PR

**Pull request closed without merging**
