### PR TITLE
NullPointerException if no iOS device is connected on Mac PC

### PR DESCRIPTION
**Pull request by RatkoD**
NullPointerException if no iOS device is connected on Mac PC

### CODE REVIEW

**Comment by RatkoD** [comment]
Hey @saikrishna321 can you please take a look at this pull request?

**Comment by saikrishna321** [comment]
@RatkoD we are doing a null check and picking the device, you should not get NullPointerException.

**Comment by RatkoD** [comment]
I was always getting a nullPointerException on my Mac when I had just iPhone connected to it. When I hade iphone and android it was working great.

**Comment by saikrishna321** [comment]
@RatkoD i fixed this at the latest and i did try it on iOS alone. Can you pls specify the version your using

**Comment by RatkoD** [comment]
I was using c83032

**Comment by saikrishna321** [comment]
@RatkoD r u still facing this issue ?

**Comment by RatkoD** [comment]
Haven't tried with the latest release, I was using my build with this fix. Will try this days and let you know.

**Comment by saikrishna321** [comment]
if iOS device is connected then we expect IOS_APP_PATH in the config ..... in your case the properties will not have the IOS_APP_PATH ?

**Comment by saikrishna321** [comment]
@RatkoD closing as the implementation is changes now

**Pull request closed without merging**
