### PR TITLE
Added support for passing in desired capabilities when using Cucumber.

### PR DESCRIPTION
**Pull request by brtu**
I added support for passing desired caps through the @before hook in Cucumber, similarly to how the desired caps are passed with TestNG.  

Example here: 
https://github.com/brtu/AppiumTestDistribution/blob/d47594ebb40c37c62ef4a2f332e62bb15c7538e3/src/test/java/com/test/cucumber/stepdefinitions/Hooks.java#L21-L22

I also removed some duplicate code by combining some methods.  Please let me know if anything is wrong.

### CODE REVIEW

**Comment by saikrishna321** [comment]
@brtu Thanks for the PR. will review is soon. Have you ran the tests in both distribute and parallel for cucumber and TestNG ? if Yes, does it work fine ?

**Comment by brtu** [comment]
@saikrishna321 I ran tests using two iOS devices in both distribute and parallel for cucumber and it worked well.  I did not test it with TestNG (my tests are all in cucumber).

**Comment by saikrishna321** [comment]
@brtu i'm looking at your branch code, i will test on TestNG and merge

**Comment by brtu** [comment]
@saikrishna321 I see... I've added the check for IOS_APP_PATH in the logic.

**Pull request merged**
