### PR TITLE
Fix for the system profiler device identifier

### PR DESCRIPTION
**Pull request by RatkoD**
Apparently, when you run the command for listing the UDID of the
attached devices from java, it concatenates the UDIDs of all attached
devices. This change splits the concatenated string into separate
strings from 40 characters.

### CODE REVIEW

**Comment by saikrishna321** [comment]
@RatkoD CI is failing .. can you please check and the system_profiler seems wrong

**Comment by SrinivasanTarget** [comment]
@RatkoD correct command should be:
```system_profiler SPUSBDataType | sed -n -E -e '/(iPhone|iPad|iPod)/,/Serial/s/ Serial Number: (.+)/\1/p'```

**Comment by RatkoD** [comment]
The extra backslash is for escaping the backslash. I don't know why it's not building, I've build it locally and it works and I'm using it. Let me check one more that that the commit is right.

**Comment by saikrishna321** [comment]
@RatkoD 

https://travis-ci.org/saikrishna321/AppiumTestDistribution/builds/147244725#L1946

you need to fix these style check

**Comment by RatkoD** [comment]
Finally!!! My firs PR ever! :)

Thanks for the patience.

**Pull request merged**
