### PR TITLE
Added support for launching devices on a subgroup of udids, also fixed some miscellaneous

### PR DESCRIPTION
**Pull request by brtu**
This PR adds support for passing in a list of device ids to the test runner so that only specified devices (and not all connected devices) will run.  Also fixed some issues with a static AndroidConfiguration that had problems with using adb commands and some spelling/formatting fixes.

Example test runner:

```
public class RunnerCukes {
    @Test 
    public void testCukesRunner() throws Exception {
    	List<String> deviceList = Arrays.asList("udid1", "udid2", "udid3");
    	ParallelThread cucumberParallelThread = new ParallelThread(deviceList);
        boolean hasFailures = cucumberParallelThread.runner("output");
        Assert.assertFalse(hasFailures, "Testcases have failed in parallel execution");
    }
}
```

Please let me know if it has any issues.

### CODE REVIEW

**Comment by saikrishna321** [comment]
@brtu thanks for the PR. Few checks, i see your passing the UDID list from the Runner class , can we also send it from ENV?

**Comment by brtu** [comment]
@saikrishna321 
Yes, the user can implement the logic in the Runner class on how to get the udid list.  I pass it in from the environment variables, and it would look like this:

command to start runner
`mvn clean -Dtest=RunnerCukes test -Dudid=udid1,udid2,udid3`

Example test runner
```
public class RunnerCukes {
    @Test 
    public void testCukesRunner() throws Exception {
        String udidParam = System.getProperty("udid");
        String[] parts = udidParam.split(",");
    	List<String> deviceList = Arrays.asList(parts);
    	ParallelThread cucumberParallelThread = new ParallelThread(deviceList);
        boolean hasFailures = cucumberParallelThread.runner("output");
        Assert.assertFalse(hasFailures, "Testcases have failed in parallel execution");
    }
}
```

**Comment by brtu** [comment]
@saikrishna321 I just made a commit to fix the issue with multiple Appium servers spawning while keeping fix https://github.com/saikrishna321/AppiumTestDistribution/issues/154.  I updated the project to ExtentReports 3.0.1 which supports single tests with multiple categories and made changes to the logic accordingly.  Please take a look when you have time.

**Comment by saikrishna321** [comment]
@brtu i did see some breaking changes on extent v3.0.1. let me test against your branch.

**Comment by saikrishna321** [comment]
@brtu did u test this against testNG?

**Comment by brtu** [comment]
@saikrishna321 No, I didn't

**Comment by saikrishna321** [comment]
@brtu i broke it when i was refactoring .. fixed now

**Pull request merged**
