### PR TITLE
Support APK/IPA in URL download and Support get bundle ID from IPA and get package name/launch activity from APK

### PR DESCRIPTION
**Pull request by ansonliao**
Hi @saikrishna321,
Added some functions that support download APK/IPA from a URL;
Added some functions that parse APK to get package name and launch activity of APK, parse IPA to get bundle ID.

### CODE REVIEW

**Comment by saikrishna321** [comment]
@ansonliao this branch has conflicts and i dont see why so many changes ..... looks like you did upstream the forked repo.. 

Can you please fork the repo again and then make your changes n send a PR please

**Comment by ansonliao** [comment]
@saikrishna321 
After I forked the project, the AppiumTestDistribution.jar version setup in POM.xml is 2.8.x.

look like I can't fork the latest version code of AppiumTestDistribution.

please advise.

**Comment by saikrishna321** [comment]
from your repo delete the repo and fork again .. this will give u the latest ..

**Comment by ansonliao** [comment]
@saikrishna321 
OK now, I will create PR tomorrow as the code saved at the company's machine

**Comment by saikrishna321** [comment]
@ansonliao sure.. closing this

**Pull request closed without merging**
